compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs

# https://yarnpkg.com/configuration/yarnrc#npmMinimalAgeGate
npmMinimalAgeGate: "5d"
# https://yarnpkg.com/configuration/yarnrc#enableScripts
enableScripts: false
