#!/usr/bin/env tsx
/**
 * Checks hand-written docs pages against the published OpenAPI spec.
 *
 * Endpoint reference pages are generated by `yarn scrape:api` and guarded by CI,
 * but guide and tool pages restate the same facts by hand and can drift silently.
 * A wrong enum value or a missing required field produces a 400 on copy-paste,
 * which is worse for agents than for humans: an agent has no way to tell that the
 * page it is reading disagrees with the schema next to it.
 *
 * Four checks:
 *   1. enum values    - every `field: "value"` in a code block must be in the schema enum
 *   2. required fields - every SDK create/generate call must pass the required top-level fields
 *   3. code samples    - the spec's own samples must only pass parameters the spec defines
 *   4. reference index - `api-reference/overview.mdx` must list exactly the spec's paths
 *
 * A code block can opt out with an `api-drift-ignore` comment on the fence line,
 * for deliberately partial snippets.
 *
 * Usage: yarn check:api-drift
 */

import fs from "node:fs";
import path from "node:path";

type Schema = {
  type?: string;
  enum?: string[];
  required?: string[];
  properties?: Record<string, Schema>;
  deprecated?: boolean;
};

type Spec = {
  paths: Record<
    string,
    Record<string, { requestBody?: { content: Record<string, { schema: Schema }> } }>
  >;
};

const SPEC_PATH = "api-reference/openapi.json";
const OVERVIEW_PATH = "api-reference/overview.mdx";
const SEARCH_DIRS = ["tools", "integration", "get-started"];

const spec: Spec = JSON.parse(fs.readFileSync(SPEC_PATH, "utf8"));

const failures: string[] = [];

const snakeToCamel = (s: string) => s.replace(/_(.)/g, (_, c: string) => c.toUpperCase());

/** `/v1/ai-image-generator` -> `ai_image_generator`, which is also the SDK resource name. */
const resourceFromPath = (p: string) => p.replace("/v1/", "").replace(/-/g, "_");

const bodySchema = (p: string): Schema | undefined =>
  spec.paths[p]?.post?.requestBody?.content?.["application/json"]?.schema;

/** Enum-typed fields, keyed by leaf name, for one endpoint. */
function enumFields(schema: Schema | undefined): Map<string, string[]> {
  const found = new Map<string, string[]>();
  const walk = (s: Schema | undefined) => {
    if (!s?.properties) return;
    for (const [key, value] of Object.entries(s.properties)) {
      if (value.enum) found.set(key, value.enum);
      if (value.properties) walk(value);
    }
  };
  walk(schema);
  return found;
}

type CodeBlock = { body: string; line: number; ignored: boolean };

function codeBlocks(source: string): CodeBlock[] {
  const blocks: CodeBlock[] = [];
  const lines = source.split("\n");
  let start = -1;
  let fence = "";
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (start === -1 && line.startsWith("```")) {
      start = i;
      fence = line;
    } else if (start !== -1 && line.trim() === "```") {
      blocks.push({
        body: lines.slice(start + 1, i).join("\n"),
        line: start + 1,
        ignored: fence.includes("api-drift-ignore"),
      });
      start = -1;
    }
  }
  return blocks;
}

type CallSite = { endpoint: string; args: string; elided: boolean };

/** Text between the call's parentheses, so nested objects stay intact. */
function argsAfter(body: string, open: number): string {
  let depth = 0;
  for (let i = open; i < body.length; i++) {
    const char = body[i];
    if (char === "(") depth++;
    else if (char === ")") {
      depth--;
      if (depth === 0) return body.slice(open + 1, i);
    }
  }
  return body.slice(open + 1);
}

/** SDK create/generate calls in a code block, resolved to their endpoint. */
function callSitesIn(body: string): CallSite[] {
  const sites: CallSite[] = [];
  for (const endpoint of Object.keys(spec.paths)) {
    if (!bodySchema(endpoint)) continue;
    const resource = resourceFromPath(endpoint);
    const pattern = new RegExp(
      `\\.(?:${resource}|${snakeToCamel(resource)})\\.(?:create|generate)\\s*\\(`,
      "g"
    );
    for (const match of body.matchAll(pattern)) {
      const args = argsAfter(body, match.index + match[0].length - 1);
      // `...` anywhere means the snippet is deliberately abbreviated.
      sites.push({ endpoint, args, elided: /(^|[\s,{[])\.\.\.($|[\s,}\]])/.test(args) });
    }
  }
  return sites;
}

function checkEnumValues(file: string, block: CodeBlock, site: CallSite) {
  for (const [field, allowed] of enumFields(bodySchema(site.endpoint))) {
    const pattern = new RegExp(
      `["']?\\b(?:${field}|${snakeToCamel(field)})["']?\\s*[:=]\\s*["']([^"']+)["']`,
      "g"
    );
    for (const match of site.args.matchAll(pattern)) {
      if (!allowed.includes(match[1])) {
        failures.push(
          `${file}:${block.line} — ${site.endpoint} rejects ${field}="${match[1]}". ` +
            `Allowed: ${allowed.join(", ")}`
        );
      }
    }
  }
}

function checkRequiredFields(file: string, block: CodeBlock, site: CallSite) {
  const schema = bodySchema(site.endpoint);
  const passed = (field: string) =>
    new RegExp(`["']?\\b(?:${field}|${snakeToCamel(field)})["']?\\s*[:=]`).test(site.args);

  const report = (field: string) =>
    failures.push(
      `${file}:${block.line} — ${site.endpoint} requires ${field}, not passed in this call`
    );

  for (const field of schema?.required ?? []) {
    if (!passed(field)) report(field);
  }

  // Nested required fields only matter once their parent object is being passed.
  for (const [field, nested] of Object.entries(schema?.properties ?? {})) {
    if (!nested.required || !passed(field)) continue;
    for (const child of nested.required) {
      if (!passed(child)) report(`${field}.${child}`);
    }
  }
}

function checkPages() {
  const files: string[] = [];
  const walk = (dir: string) => {
    for (const entry of fs.readdirSync(dir)) {
      const full = path.join(dir, entry);
      if (fs.statSync(full).isDirectory()) walk(full);
      else if (entry.endsWith(".mdx")) files.push(full);
    }
  };
  SEARCH_DIRS.filter((d) => fs.existsSync(d)).forEach(walk);

  for (const file of files) {
    const source = fs.readFileSync(file, "utf8");
    for (const block of codeBlocks(source)) {
      if (block.ignored) continue;
      for (const site of callSitesIn(block.body)) {
        if (site.elided) continue;
        checkEnumValues(file, block, site);
        checkRequiredFields(file, block, site);
      }
    }
  }
}

/**
 * The samples the spec carries must only pass parameters the spec still defines.
 *
 * `cleanup-deprecated-fields.js` strips deprecated parameters from both the schemas and the
 * samples on every spec refresh, but it can only remove bindings it knows how to parse. This
 * catches whatever it missed, on the pull request that introduces it rather than in a nightly log.
 */
function checkCodeSamples() {
  // Bindings that belong to the SDK call rather than the request body.
  const sdkOptions = new Set([
    "client",
    "res",
    "token",
    "data",
    "type_",
    "wait_for_completion",
    "download_outputs",
    "download_directory",
    "waitForCompletion",
    "downloadOutputs",
    "downloadDirectory",
  ]);

  const camelToSnake = (s: string) => s.replace(/([A-Z])/g, "_$1").toLowerCase();

  // Deprecated parameters count as undefined: the cleanup strips them from the schema, and a
  // sample that still passes one is the exact drift this is looking for.
  const propertyNames = (schema: Schema | undefined, found = new Set<string>()) => {
    for (const [name, property] of Object.entries(schema?.properties ?? {})) {
      if (property.deprecated === true) continue;
      found.add(name).add(snakeToCamel(name)).add(camelToSnake(name));
      propertyNames(property, found);
    }
    if (schema?.items) propertyNames(schema.items, found);
    return found;
  };

  /**
   * Names bound to a value in a sample.
   *
   * Quoted keys have to be read without reading inside strings generally, or a URL's scheme looks
   * like a binding: `"https://example.com"` is not a field called `https`.
   */
  const boundNames = (source: string) => {
    const names: string[] = [];
    const after = (index: number) => source.slice(index).match(/^\s*[:=](?!=)/);

    for (let i = 0; i < source.length; i++) {
      const char = source[i];

      if (char === '"' || char === "'" || char === "`") {
        const start = i + 1;
        i++;
        while (i < source.length && source[i] !== char) {
          if (source[i] === "\\") i++;
          i++;
        }
        const contents = source.slice(start, i);
        if (/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(contents) && after(i + 1)) names.push(contents);
        continue;
      }

      if (/[a-zA-Z_]/.test(char) && !/[a-zA-Z0-9_.]/.test(source[i - 1] ?? " ")) {
        const word = source.slice(i).match(/^[a-zA-Z_][a-zA-Z0-9_]*/)![0];
        i += word.length - 1;
        if (after(i + 1)) names.push(word);
      }
    }

    return names;
  };

  for (const [endpoint, methods] of Object.entries(spec.paths)) {
    const operation = methods.post as
      | { "x-codeSamples"?: { lang: string; source: string }[] }
      | undefined;
    const schema = bodySchema(endpoint);
    if (!operation?.["x-codeSamples"] || !schema) continue;

    const defined = propertyNames(schema);

    for (const sample of operation["x-codeSamples"]) {
      // Python and JavaScript are the tabs readers see first, and the two the SDKs mirror most
      // closely; the others carry enough language scaffolding to make bare name matching noisy.
      if (sample.lang !== "python" && sample.lang !== "javascript") continue;

      for (const name of new Set(boundNames(sample.source))) {
        if (defined.has(name) || sdkOptions.has(name)) continue;
        failures.push(
          `${SPEC_PATH} — the ${sample.lang} sample for ${endpoint} passes ${name}, ` +
            `which the request schema does not define`
        );
      }
    }
  }
}

/** The reference index is hand-written, so it is the one page that can list paths the API lacks. */
function checkReferenceIndex() {
  const source = fs.readFileSync(OVERVIEW_PATH, "utf8");
  const listed = new Set(
    [...source.matchAll(/`(GET|POST|DELETE) ([^`]+)`/g)].map(
      (m) => `${m[1]} ${m[2].replace(/:([a-zA-Z_]+)/g, "{$1}")}`
    )
  );
  const actual = new Set(
    Object.entries(spec.paths).flatMap(([p, methods]) =>
      Object.keys(methods).map((method) => `${method.toUpperCase()} ${p}`)
    )
  );

  for (const entry of actual) {
    if (!listed.has(entry)) failures.push(`${OVERVIEW_PATH} — missing ${entry}`);
  }
  for (const entry of listed) {
    if (!actual.has(entry))
      failures.push(`${OVERVIEW_PATH} — lists ${entry}, which is not in the spec`);
  }
}

checkPages();
checkCodeSamples();
checkReferenceIndex();

if (failures.length > 0) {
  console.error(`Found ${failures.length} mismatch(es) between the docs and ${SPEC_PATH}:\n`);
  for (const failure of failures) console.error(`  ${failure}`);
  console.error(
    "\nFix the page, or add api-drift-ignore to the code fence if the snippet is deliberately " +
      "partial. For samples carried in the spec itself, teach cleanup-deprecated-fields.js to " +
      "scrub the parameter or add a rewrite to code-sample-migrations.json."
  );
  process.exit(1);
}

console.log("docs match the OpenAPI spec");
